# This is a basic workflow to help you get started with Actions

name: Docker Executor
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  workflow_dispatch:

jobs:
  container:
    # runs-on: wsl-1
    runs-on: win10
    container: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          whoami
          pwd
          ls -latr
          lsb_release -a
          hostnamectl
          cat /proc/cpuinfo

      - name: Run a multi-line script
        run: |
          whoami
          pwd

          ls -latr /etc
          ls -latr /bin